### ISSUE TITLE
Отображение генераторов на миникарте

### ISSUE THREAD

**Issue by fe-ed** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#134]
### Description

Генераторов на миникарте нет ни при каких условиях, от модульности вроде не зависит. Долго копался и нее нашел причину такой ужасной пропажи, оставляю багрепорт бравым кодерам.

### Test Merges

[Blip fix](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/85)

**Comment by Helg2** [comment]
Сезам закройся!
