### ISSUE TITLE
Сломанное отображение спрайта пояса двухстволки на кукле

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#155]
### Description

Я приметил это только сейчас, ибо мне всегда казалось что оружие в руках и перчатки перекрывают спрайт пояса на кукле. Но оказалось что нет. Если двухстволка лежит в поясе - спрайт магически испаряется с тела, пока ты не вытащишь оружие.
А если в suit storage - так вообще что с оружием что без
Подозреваю что проблема давняя и растёт ещё с того момента когда спрайт пояса ломался если в него положить ДБ без патрон, с одним патроном и раскрытым: https://github.com/tgstation/TerraGov-Marine-Corps/pull/11897

### Test Merges

Round ID: 5566
BYOND Version: 515.1613
Server revision compiled on: 2023-11-20T16:55:32+00:00
Master commit: [0d7d88d1a19dbc35ce3b387b2792571e3719b284](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/0d7d88d1a19dbc35ce3b387b2792571e3719b284)
The following pull requests are currently test merged:
[#124: 'Buff scout cloak [NON-MODULAR]' by Ghostkokos at commit 75a8769dbc](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/124)
[#140: 'More Queen Screeches' by Waselon at commit 88dbe8f2c7](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/140)

Local commit: a68f5578f90f52fa9d1dce639fac30c4b51f7618
Server tools version: 5.16.4

### Reproduction Steps

1. Одеть пояс для двухстволки с оружием внутри на слот пояса и/или suit storage
2. Вытащить и положить ДБ из пояса.
3. Проявление ошибки: пропажа отображения пояса на кукле

### Screenshots

![Screenshot_17](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/1b2b2e42-6023-4dba-8d04-3e2ac39edfaf)
![Screenshot_18](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/5a3481cd-987d-4f72-9a05-ada8842c34a9)
![Screenshot_19](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/d6471de2-5941-465a-87b4-03e1d0c7ebd9)
![Screenshot_20](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/5a6df12d-118e-4388-b9b8-edee6fb2b4b2)
![Screenshot_21](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/572fd4cd-223d-4a7c-bb65-9f6d03cf7e1a)
![Screenshot_22](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/b9a28d02-1115-432e-9525-61339d466e32)
![Screenshot_23](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/6c88be2e-2273-4a14-a47c-492994f805c0)

**Comment by LoneAsket** [comment]
Посмотрим.

**Comment by LoneAsket** [comment]
Спрайты вроде бы все исправлены.
Спрайта двушки в слоте SUIT нет по причине того, что у нас и оффов банально нет спрайта для них именно в слоте SUIT.
Если кто-то сделает спрайт, пингуйте меня, я залью.
Если никто не собирается рисовать для этого спрайт, то @fe-ed закроешь.
