### ISSUE TITLE
No berets?

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#157]
### Description

Раньше, до ребейза, играя на роботе, ты спокойно мог носить на голове смешные головные уборы типа берета, банданы и прочего. Сейчас же это невозможно. 

Верните железкам смешные шляпы.

### Test Merges

Round ID: 5568
BYOND Version: 515.1613
Server revision compiled on: 2023-11-21T17:36:23+00:00
Master commit: [0d7d88d1a19dbc35ce3b387b2792571e3719b284](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/0d7d88d1a19dbc35ce3b387b2792571e3719b284)
The following pull requests are currently test merged:
[#124: 'Buff scout cloak [NON-MODULAR]' by Ghostkokos at commit 75a8769dbc](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/124)
[#140: 'More Queen Screeches' by Waselon at commit 13d176dd6d](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/140)

Local commit: 12d0a6e4b253730f8d77efe40a78cf8c025162dc
Server tools version: 5.16.4

### Reproduction Steps

1. Зайти в игру за расу робота.
2. Взять любой головной убор из списка предлагаемых вендором что не является каской.
3. Баг обнаружен - невозможность носить шляпы.

### Screenshots

![Screenshot_32](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/5ea2b9f1-b8bf-4e58-b723-312fe9dfa11e)

**Comment by LoneAsket** [comment]
Взял.
