### ISSUE TITLE
Сломаный индикатор трупа робота на медхуде

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#159]
### Description

Труп робота продолжает моргать на медхуде и после того как его таймер в 5 минут истёк, создавая иллюзию того что дефибриляция всё ещё возможна.

### Test Merges

Round ID: 5583
BYOND Version: 515.1613
Server revision compiled on: 2023-11-21T17:36:23+00:00
Master commit: [0d7d88d1a19dbc35ce3b387b2792571e3719b284](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/0d7d88d1a19dbc35ce3b387b2792571e3719b284)
The following pull requests are currently test merged:
[#124: 'Buff scout cloak [NON-MODULAR]' by Ghostkokos at commit 75a8769dbc](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/124)
[#140: 'More Queen Screeches' by Waselon at commit 13d176dd6d](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/140)

Local commit: 12d0a6e4b253730f8d77efe40a78cf8c025162dc
Server tools version: 5.16.4

### Reproduction Steps

1. Заспавнить робота и умертвить его.
2. Подождать 5 минут до состояния невозможности реанимации
3. Посмотреть на труп через медхуд
4. Баг обнаружен: мигание продолжается даже по истечению времени.

### Screenshots

![Screenshot_33](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/13ca5010-a5c5-481b-833b-f2207ae8df50)

**Comment by fe-ed** [comment]
Поправлю, просто я немного ленивая жопа..

**Comment by Ghostkokos** [comment]
Пофикшено фидом
