### ISSUE TITLE
TGMC slouch hat не отображается на кукле

### ISSUE THREAD

**Issue by CabbageOnTable** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#162]
### Description

TGMC slouch hat не отображается на кукле
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/09fe17e9-64f5-4754-847d-85501c6971b3)

### Test Merges

Round ID: 5603
BYOND Version: 515.1613
Server revision compiled on: 2023-11-22T17:42:27+00:00
Master commit: [4c26cce1c9e2d6da8e8845197e57a5af41a2d630](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/4c26cce1c9e2d6da8e8845197e57a5af41a2d630)
The following pull requests are currently test merged:
[#139: 'Maybe fix of box som modules [Modular]' by Helg2 at commit 26d83371ce](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/139)
[#138: 'Maybe fix of 'Fix-Stat-Panel' unrecognized verb error [Non-modular]' by Helg2 at commit 750c63e839](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/138)

Local commit: 36ac41725a2c271f0a048815ad0476875abe9525
Server tools version: 5.16.4

хз нахуя эта инфа, это после ребейза так

### Reproduction Steps

Заходим за марика, кукла человек, берем из вендора с одеждой TGMC slouch hat и надеваем 
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/c5afbff7-ec37-4d0b-96f1-7fe3116751aa)

**Comment by LoneAsket** [comment]
Фикс уже лежит на Гитхабе.

**Comment by CabbageOnTable** [comment]
На тест мерже все работает хорошо, закрываю ишуй
