### ISSUE TITLE
Chemrette packet problems

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#168]
### Description

Пачка сигарет, называемая "Chemrette packet" немного баганутая. В отличии от обычной пачки Lucky Stars из сиго-вендора у неё есть больше места(18 и 25 слотов), что я показал на скриншоте 1. И если попытаться всунуть больше сигарет чем задано изначально при выдаче - спрайт пачки исчезает.

Учитывая что толку от напихивания лишних сигарет в пачку никаких, ибо пачка с изменённым составом и количеством сигарет не сохраняется - то надо заодно пофиксить и это.

### Test Merges

Round ID: 5624
BYOND Version: 515.1613
Server revision compiled on: 2023-11-22T17:42:27+00:00
Master commit: [4c26cce1c9e2d6da8e8845197e57a5af41a2d630](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/4c26cce1c9e2d6da8e8845197e57a5af41a2d630)
The following pull requests are currently test merged:
[#139: 'Maybe fix of box som modules [Modular]' by Helg2 at commit 26d83371ce](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/139)
[#138: 'Maybe fix of 'Fix-Stat-Panel' unrecognized verb error [Non-modular]' by Helg2 at commit 750c63e839](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/138)

Local commit: 36ac41725a2c271f0a048815ad0476875abe9525
Server tools version: 5.16.4

### Reproduction Steps

1. Взять пачку "Chemrette packet"
2. Засунуть в пачку больше сигарет чем выдано
3. Баг обнаружен: пачка испарилась.

### Screenshots

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/05a06fc3-4c8d-4e16-b40b-8ab6f1870cba)
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/ab4eedfb-b22e-4a28-b6e5-29b864171463)

**Comment by LoneAsket** [comment]
Гляну.
