### ISSUE TITLE
Увеличить количество Т-Газ гранат в марин-вендоре с 10 до 30

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#169]
Вот эта маленькая фиолетовая граната расходится как горячий пирожок в вендоре морпехов, и шансы её получить даже спустя 2 минуты от старта раунда уже стремятся к нулю, поскольку какой-нибудь ПФЦ-морпех сохранил себе лодаут с 18 гранатами на 2 поуча и гранатный модуль на броню, по итогу за раунд использовав ну штуки 3-4 и сдохнув, прожав ДНР после первой же смерти.
И всё, ищи-свищи гранаты и покупай коробочку на 25 штук в Карго за 700 поинтов.

Потому что б увеличить шанс застать её в вендоре хотя б до 10 минуты от начала раунда - предлагаю изменить количество на 30 гранат.
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/9eefef0a-a7c3-451c-81bd-f3f9b2f0890e)

**Comment by LegateBebranius** [comment]
Я в госте глянул не в вальгалле а в обычном марин вендоре - ситуация то ещё хуже. Их не 20. Их сука 10. Оффы - сами знаете кто.

**Comment by Dgeen** [comment]
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/187
