### ISSUE TITLE
Кривые модули у роботов

### ISSUE THREAD

**Issue by helper-2** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#173]
### Description

После введения Саровских броне модулей для ягера, эти самые модули появились и у роботов. Они слишком выделяются, иногда не подходят под спрайт (например тюр для М и Н), и их нельзя красить. Причем есть даже баг, при котором этот самый спрайт модуля исчезает, если собрать ещё одну такую же бронь, с тем же модулем и положить ее обратно в вендор, то спрайт модуля исчезнет. Претензий к модулям хранения нету. 

### Test Merges

Со времён введения Саровских броне модулей для ягера

### Reproduction Steps

1. Взять броню робота.
2. Взять тюр, ход или щит.
3. Одеть выбранный модуль на броню.
4. Словить кринж.

**Comment by Helg2** [comment]
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/93882977/0336eb46-4fdb-42d6-9bba-c154d080a2f4)
@Dark-Umbrella

**Comment by Ghostkokos** [comment]
Исправлено Саро полагаю, пиар замержен при повторном тесте косяков не обнаружил
