### ISSUE TITLE
Т500 - некорректно отображается магнитка, отсутствуют пакеты обычных патронов

### ISSUE THREAD

**Issue by CabbageOnTable** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#177]
### Description

Для Т500 предусмотренны пакеты для квин киллера они уже допустим лежат с раундстарта в вендоре, но вот для обычных патронов их нету, только спидлодеры. Также на нем хуево отображается магнитка (раньше ее вроде вообще просто не показывало)

### Test Merges

Round ID: 5639
BYOND Version: 515.1613
Server revision compiled on: 2023-11-25T14:33:40+00:00
Master commit: [def055d9fc8ba23ee37061636115fab368dba2b3](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/def055d9fc8ba23ee37061636115fab368dba2b3)
The following pull requests are currently test merged:
[#139: 'Maybe fix of box som modules [Modular]' by Helg2 at commit 26d83371ce](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/139)
[#167: 'Some changes to destroying heart with sharp tools process.' by Helg2 at commit 3a385ae2aa](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/167)
[#166: '[FIX][MODULAR] Fix icon's for belts' by LoneAsket at commit b1b35fda78](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/166)
[#164: 'FC Updates' by Waselon at commit aaab6bccf5](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/164)
[#160: '[FIX][MODULAR] Allow beret's for robot' by LoneAsket at commit c5815f9831](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/160)

Local commit: 56eda414d3fc0b0282f3cb7fdbf64955ef59c28e
Server tools version: 5.16.4

### Reproduction Steps

1.) Заходим в раунд за морпеха (в вальгале нету т500)
2.) Берем из оружейного вендора Т500 кейс, внутри сам т500 (см. скрин ниже)
3.) Надеваем магнитку 
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/88bdbb63-4de2-484e-b650-325b8526a787)

### Screenshots

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/77cd3c49-72c1-4045-81f1-88440a85452d)

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/5f62ad2e-f709-4eda-b946-94b1160e6a49)

**Comment by CabbageOnTable** [comment]
Скрины из старого билда

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/1d8d5e24-9b19-4659-a8ed-a45ad74babc0)

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/114332059/d62b6b8f-c619-49cb-bf5b-1f28c35643ed)

**Comment by LoneAsket** [comment]
Исправлено. @fe-ed
