### ISSUE TITLE
Хайвмайнд не может ставить траву на ФОБе и Нормандии

### ISSUE THREAD

**Issue by Deal5** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#191]
### Description

ХМ скорее всего должен уметь это делать.

### Test Merges

-

### Reproduction Steps

1. Зайдите за Хайвмайнда
2. Попробуйте поставить траву на территорию ФОБа
3. ???

### Screenshots

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/84900425/828a1ee0-a163-4667-8c7a-5093b6640c9b)

**Comment by CabbageOnTable** [comment]
Это сделано потому чтобы хм немог попасть на шип и вьебашить сило там например или турели в крио

**Comment by Frampo123** [comment]
Там смешнее есть: ты МОЖЕШЬ срать где был Аламо, но не можешь срать там, где был ТАД. База
