### ISSUE TITLE
[TM-BUG] Химера-Клон это SSD моб.

### ISSUE THREAD

**Issue by Ro2tCrab** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#239]
# Суть проблемы.
За Химеру может войти Гост.
# Как повторить?
Попробовать взять из ССД мобов Клона.
# Дополнительная информация.
Есть вероятность возможности диэвольнуть клона в другую касту и фармить лявр (?).

**Comment by Ro2tCrab** [comment]
Химера уже давно не в ТМ.
Закрыто?

**Comment by Ghostkokos** [comment]
Закрыто
