### ISSUE TITLE
Ксеносы не могут нормально смотреть другой конец лестниц.

### ISSUE THREAD

**Issue by Helg2** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#275]
Если перевести лестницу на себя, чтобы посмотреть что на другом конце лестницы, за ксеноса, то ты не сможешь вернуть себе зрение если не прожмёшь `Cancel Camera View`
У хуманов такой проблемы нету.
Возможно проблема в кривой структуре `/mob/living/carbon/xenomorph/reset_perspective(atom/A)`

**Comment by LoneAsket** [comment]
Не смог повторить баг, чтобы прям нельзя было вернуть зрение.
Спокойно делаю шаг от лестницы и вид возвращается обратно.
Однако подтверждаю, что зрение возвращается с некоторой задержкой, где-то в секунду
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/59748469/cf643716-ee67-40a7-a661-50069163650c)

**Comment by LoneAsket** [comment]
Также забавный графический глич, если на том же Сулако за человека делаешь шаг вниз после просмотра лестницы.
Пропадает отображение некоторых эирлоков, пока не апдейтнется или хуман не сделает шаг куда-нибудь.
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/59748469/413669a7-e679-4a05-a794-87e046e23927)
