### ISSUE TITLE
[BUG] Задержка между выстрелами

### ISSUE THREAD

**Issue by eumara31** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#285]
### Description

У оружия общая задержка между выстрелами, особенно ярко это заметно при стрельбе из оружия с долгой задержкой, например из рейлгана:
Если вы выстрелите из рейлгана, тут же возьмёте любое другое оружие и попытаетесь выстрелить, игра выдаст вам следующее сообщение в чат - "The <...> is not ready to fire again!"

### Test Merges

BYOND Version: 515.1623
Server revision compiled on: 2023-12-26
Master commit: [7d96454043e2978ffe6e3a7ef5140fc4428fefde]
Local commit: 2fa54c69c4d5196834a89832872255b195c9a27a
Баг не связан с моим локальным коммитом, баг воспроизводится и на рабочей версии билда, стоящей на сервере.

### Reproduction Steps

1. Взять оружие X
2. Выстрелить
3. Успеть взять оружие Y до конца задержки между выстрелами оружия X
4. Успеть выстрелить
5. Получить в чат сообщение о невозможности произвести выстрел, хотя из оружия Y вы могли вообще не стрелять

**Comment by Dgeen** [comment]
Не баг
