### ISSUE TITLE
Хуйня для завода патронов на СГ62 не приезжает

### ISSUE THREAD

**Issue by Suchinessa** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#307]
### Description

Меня наебали на 500 поинтов

### Test Merges

ыаааааа

### Reproduction Steps

1. Заказать SG-62 ammo drum parts refill
2. Поднять лифт
3. Открыть коробку и увидеть что она пустая
4. Понять что ТерраГов наебунькало вас на 250 поинтов

**Comment by Helg2** [comment]
На оффах уже пофикшено.
