### ISSUE TITLE
[Feature] Вернуть GL-54 магазин с колючей проволокой.

### ISSUE THREAD

**Issue by Ro2tCrab** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#315]
# Суть
У Aiirbust GL-54 гранатомета помимо танглфута, зажигательных и взрывных есть магазин колючей проволки.
Собственно предлагаю их вернуть как эксклюзивный набор для инженеров и рецепт карго завода.
# Чем это хорошо?
Немного контента инженерам? Количество этих гранат всегда можно будет подправить стоимостью обоймы в вендоре, но ориентировочно - 15 поинтов за обойму из 10 гранат.

### P.s : В коде уже должна быть сама обойма.

**Comment by fe-ed** [comment]
Коллегией балансеров оффов было решено, что пушка стреляющая строениями - имба, и я с ними полностью согласен
