### ISSUE TITLE
[Feature] Сделать OOC открытым до начала раунда

### ISSUE THREAD

**Issue by Ro2tCrab** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#318]
Что бы в лобби не было тихо.

**Comment by Ro2tCrab** [comment]
> На локалке всё работает, админ ишью?

Я что то напутал?
У меня абсолютно чистый аккаунт BYOND, но OOC нет.
Проверю еще раз.

**Comment by CabbageOnTable** [comment]
> Я что то напутал? У меня абсолютно чистый аккаунт BYOND, но OOC нет. Проверю еще раз.

Проверь настройки чата и в преферансах тоглл оос

**Comment by Ro2tCrab** [comment]
Это был прикол Интернет Эксплоррера.
Тема закрыта.

**Comment by Ro2tCrab** [comment]
Сам закрою как дойду до компьютера.
