### ISSUE TITLE
[Feature] Диспенсер может пополнять пустые обоймы.

### ISSUE THREAD

**Issue by Ro2tCrab** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#345]
# Суть.
Клик по диспенсеру обоймой пополнит её. Диспенсер сможет пополнить любую **стандартную** обойму до 7500 **стандартных пуль** без перезарядки.
Диспенсер можно перезарядить специальным предметом по 2500 пуль каждый, который можно хранить в инвентаре самого диспенсера.
# Чем это хорошо?
Функционал диспенсеру.
Может этот предмет наконец **найдет применение дальше персонального сейфа** **руках команды маринов**

**Comment by Ghostkokos** [comment]
Полагаю не актуально с учётом твоего нового ишуя https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/issues/392

**Comment by Ro2tCrab** [comment]
> Полагаю не актуально с учётом твоего нового ишуя https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/issues/392

Так и есть.
