### ISSUE TITLE
Странная дистацния у martini-henry 

### ISSUE THREAD

**Issue by BigGnida** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#431]
### Description

У мартини генри эффективная дистацния стрельбы от 30 до 40. ей либо ввести возжность снова целится либо уменьшить эффективную дистанцию 

### Test Merges

БЕРЁМ СМОТРИМ ОПИСАНИЕ ПАТРОНА . ХМММММ ЭФФЕКТИВНАЯ ДИСТАНЦИЯ СТРЕЛЬБЫ ОТ 30 ДО 40 ТАЙЛОВ БЕЗ ПРИЦЕЛИВАНИЯ ЧЕ-ТА ТУТ НЕ ТАК 

### Reproduction Steps

Ей либо ввести возможность снова целится либо уменьшить эффективную дистанцию стрельбы хотя бы от 15 до 3

### Screenshots

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/160073917/4039b8d9-285c-41f0-8c1f-b6eb0cfc5cf9)

**Comment by homexp13** [comment]
Эффективная дистанция, это дистанция после которой шанс попасть уменьшается, если ты её уменьшишь на дальних дистанциях шанс попасть меньше будет 😕 
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/52973135/d8febe88-cf7f-447c-9242-d3f597569a8b)
за промахи вблизи отвечает accurate_range_min, а он и так 0
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/52973135/76e9b74f-a244-4ce8-9613-02cafa5f122c)
Так что СКИЛЛ ИШУЙ, вместо бафа предложил нерф из за незнания механик
