### ISSUE TITLE
[BUG] Нельзя зайти за хаггера через Карриера.

### ISSUE THREAD

**Issue by Ro2tCrab** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#432]
# Суть.
Карриер может служить точкой спавна хаггеров, но госты не могут прожать его как спавн точку.
# Подробности.
Предположение: т.к что бы зайти за хаггера нужно кликнуть яйцо, то тут скорее всего та же проблема.
# Как повторить?
- Зайти за Карриера.
- Убрать резерв хаггеров.
- Пытаться использовать его как точку спавна.

**Comment by Helg2** [comment]
Могут

**Comment by Ro2tCrab** [comment]
> Могут

Тестил?

**Comment by Ro2tCrab** [comment]
> В игре и не одноразово, файлы с хаггерами и кериерром у нас вроде бы никто не трогал ближайший месяц

Yeah.. here we go. Issue destroyed. Mission accomplished.
