### ISSUE TITLE
[BUG] Поломанный спавн вещей из лодаута

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#467]
### Description

Множество вещей в вальгалле, а некоторые из них даже в раунде - при выборе сохранённого лодаута не экипируются и тем более даже не спавнятся.
На данный момент насчитаннл: медпоуч и его содержимое, старторые наборы всех ролей с вендорами за Очки, как и вещи за очки впринципе, сг62 перестал спавнится даже в раунде. Это только поверхностно собранная информация.
Некоторые вещи к тому же числятся как выданные, но на руках их нет, как стартовый набор СЛа - бинокль, свисток, с4 и так далее

### Test Merges

Round ID: 7695
BYOND Version: 515.1630
Server revision compiled on: 2024-02-29T17:51:47+00:00
Master commit: [487b0d33211d35784e55253a223a7388b0622f05](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/487b0d33211d35784e55253a223a7388b0622f05)
The following pull requests are currently test merged:
[#320: '[TM-ONLY] line of sight fix' by definitelynotspaghetti at commit 019be7e77e](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/320)
[#394: 'Warlock unfuck' by MeowEmiya at commit 855f3c93c6](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/394)
[#360: '[MODULAR] Hunter redone' by definitelynotspaghetti at commit c8af9e901b](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/360)
[#393: 'tail swep feature' by Ghostkokos at commit 0c3fac2693](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/393)
[#424: 'Второе пришествие быка (bull rework v2)' by MeowEmiya at commit 194ee9928c](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/424)
[#364: 'Remakes burst larva into `notify_ghosts` so it doesn't make you larva without your agreement.' by Helg2 at commit 5cc568c3c6](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/364)
[#447: 'Baneling removed. New minion: baneling.' by MeowEmiya at commit 2b0ca20f5a](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/447)
[#460: 'Vendor rebalance partly revert' by definitelynotspaghetti at commit 9a5aacc113](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/460)
[#464: 'Synth cant attack' by lorianss at commit 5a0d75fec7](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/464)

Local commit: 6fe477a00e20f224f241bfcde8b01b4a4afeaf48
Server tools version: 6.1.5

### Reproduction Steps

1. Зайти в Вальгаллу
2. Выбрать сохранённый лодаут на любую из 4 ролей с вещами за поинты, например СЛ: комбат рюкзак и магазин поуч с волькитными батареями
3. Экипировать данный лодаут
4. Проявление проблемы: вещи не появились

**Comment by Helg2** [comment]
Вещи не появляются только в вальгалле или и на нормальных парах? Если только в вальгалле, то на оффах уже делали фикс, можно портировать

**Comment by LegateBebranius** [comment]
> Вещи не появляются только в вальгалле или и на нормальных парах? Если только в вальгалле, то на оффах уже делали фикс, можно портировать

И в галле и как уже сказал некоторые вещи непосредственно в раунде. Как шмотье ФК например, брал недавно, сохранил для теста и в Squad Marine и в Squad Leader лодаут на него - ниче из его шмоток не далось, даже ссаный т2 тюр.

**Comment by Helg2** [comment]
Сезам закройся?

**Comment by LegateBebranius** [comment]
> Сезам закройся?

ну ты бы упомнянул этот баг репорт что ль вместе со своим фиксом
