### ISSUE TITLE
Hivemind on crash removal

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#503]
В отличии от регулярных режимов, краш известен тем что у него есть туманные области которые никаким честным образом нельзя пробить, как и содержимое внутри данных мест.
И хайвмайнд как водится, это структура. 
А теперь представьте себе что эта структура находится за туманом, что значит её невозможно достать. И игрок на ней может наспавнить бесчисленное количество резиновых стенок и кислотных болот прям под ногами у морпехов, абсолютно не боясь возмездия, ведь сколько б ты его не убивал - искоренить не выйдет. Это не входит в рамки обычного краш баланса с волновым респавном ксено.
Хотя и режим один хрен несбалансированный. Ну так давайте хоть чутка это исправим.
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/70847474-fe70-4e14-8881-eef3d95018fd)

**Comment by Helg2** [comment]
Но это же считай аналог СМО, которого хер достанешь, если он не дебил.

**Comment by LegateBebranius** [comment]
> Но это же считай аналог СМО, которого хер достанешь, если он не дебил.

Нуууууууу..... Шип раздолбать всё таки можно, упорно, расшибая голову, но можно, да и СМО не на месте стоит. А ХЛа не выкурить ни коим образом, ибо даже рейлганы отключены.

Тут можно предложить вариант запрета установки его в зоне тумана если уж под нож его не готовы пускать, но люди не поймут. Однако проблему один хер как-то надо решить, ящитаю во всяком случае, ибо меня задалбывает этот бессмертный кусок резиновой троляки.
