### ISSUE TITLE
Музыкальные инструменты не работают до начала раунда

### ISSUE THREAD

**Issue by LegateBebranius** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#505]
### Description

Название само за себя говорит: пока не начнётся раунд - музыка в инструменте играть не будет что б ты не делал, хоть кнопку воспроизведения ты и нажал.

Скорее всего потому что она так же к тикрейту привязана, ибо пока я писал ишшуй - раунд попытался запуститься, но поскольку не было ксено - ничего не вышло. Потому сыгралась только пара нот, прежде чем всё замерло.

### Test Merges

Round ID: 7999
BYOND Version: 515.1630
Server revision compiled on: 2024-03-14T12:19:33+00:00
Master commit: [a893316d6bfea704b99566fae16c658c9854c17e](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/commit/a893316d6bfea704b99566fae16c658c9854c17e)
The following pull requests are currently test merged:
[#320: '[TM-ONLY] line of sight fix' by definitelynotspaghetti at commit 019be7e77e](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/320)
[#424: 'Второе пришествие быка (bull rework v2)' by MeowEmiya at commit bcde5fa046](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/424)
[#364: 'Remakes burst larva into `notify_ghosts` so it doesn't make you larva without your agreement.' by Helg2 at commit 040936b1b0](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/364)
[#464: 'Synth cant attack' by lorianss at commit 5a0d75fec7](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/464)
[#476: 'Tyr nerf' by definitelynotspaghetti at commit 2ddac26065](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/476)
[#475: 'AP bullets' by definitelynotspaghetti at commit 2795e8d766](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/475)
[#483: 'Acid cone buff' by definitelynotspaghetti at commit 31f387a0e4](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/483)
[#478: 'synth vendor' by definitelynotspaghetti at commit c4c4b493c1](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/478)
[#470: 'Minimap body indicator fix, some health huds sprite and code changes.' by Helg2 at commit 7c0d7ebdeb](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/470)
[#466: 'Neurotoxin removal' by definitelynotspaghetti at commit 99c07a17b0](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/466)

Local commit: 60ca7c80d48753c9ddaf6a891f959591827e3ac8
Server tools version: 6.3.2

### Reproduction Steps

1. До начала старта раунда зайти в вальгаллу
2. Взять музыкальный инструмент и вбить мелоди.
3. Проблема найдена - музыки нет.

### Screenshots

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/32f9b43f-e7da-495a-8d02-467f790b808a)

**Comment by Ro2tCrab** [comment]
Не баг, большинство систем не работает до начала раунда и не должно.
