### ISSUE TITLE
[BUG] Мимир на шлем не обеспечивает защиты от газов

### ISSUE THREAD

**Issue by eumara31** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#566]
### Description

Мимир на шлем не обеспечивает стопроцентной защиты от газов, хотя в ПР 
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/485
сказано, что: "Теперь есть только модуль на шлем, который защищает ТОЛЬКО от дымов."

### Test Merges

.

### Reproduction Steps

.

**Comment by Ghostkokos** [comment]
Мимир теперь существует только как модуль на шлем. Уменьшает количество вдыхаемого дыма, но не защищает полностью.
