### ISSUE TITLE
Краш сервера при примо-разбеге на крашере

### ISSUE THREAD

**Issue by n-chursin** [Cosmic-Overlord/RU-TerraGov-Marine-Corps#568]
### Description

Уже не в первый раз делаю примо-разбег и сервер падает, не похоже на совпадение. Происходило в раундах 8140, 8419

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/108081888/f104b285-942f-4940-a4da-1b37584b7fe2)
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/108081888/402306b2-5c58-4ed2-b2f2-b931dc3af179)

### Test Merges

Local commit: 814e45a93e3f794eb9f5115824108757ab5f7a58
Server tools version: 6.3.2

### Reproduction Steps

1. Прожать примо-разбег крашера

**Comment by Helg2** [comment]
Можно закрывать наверное, пр на фикс мержнут.
